### ISSUE TITLE
Add datacenter concept to the GUI

### ISSUE THREAD

**Issue by wimpers** [openvstorage/home#12]
Open vStorage can be deployed across multiple datacenters:
- On the Failure Domains page: 
 - Add button to add DataCenter (allow to remove a DC when no racks are defined): Name, Address, City, Country
 - Add button to add Rack underneath a DC (allow to remove a rack when no nodes are assigned to it) Name
- On the Dashboard
 - Instead of displaying Failure Domains, display datacenters and racks
 - Add +/- to collapse & expand
 - In case an alba backend is flash accelerated add a [bolt symbol](http://fontawesome.io/icon/bolt/) before the name
 - In case the backend is an external one, add the [external link symbol](http://fontawesome.io/icon/external-link/)
- On the ALBA Detail page
 - Node name: use a breadcrumb style to display node name (DC > Rack > Nodename), allow to update the DC/rack.
- On vPool or vDisk detail page
 - Allow to select as DTL location a rack or DC. In case a rack is selected any node within the rack should be possible to be used as DTL location.

**Comment by wimpers** [comment]
We took the decision not to add any hierarchy to add the the multi-dc concept to the GUI. We will allow users to define their own tags and label f.e. backends with the correct labels. These labels will replace the failure domain concept.

Next to adding labels the option to indicate whether a backend is global (spread across multiple datacenters) or local within the datacenter. This will allow to define a global and a local policy for a backend. The global policy defines the resilience against datacenter failure (lose 1, 2 ,3 datacenters) while the local backend policy allows to rebuild data in case of a disk failure by only using the data from the local datacenter and without the need of data from other datacenters. This would cause less stress on the network in between datacenters.

**Comment by kvanhijf** [comment]
Closing since +/- 100% of suggestions made didn't make it to the product
See https://github.com/ovs-projects/org_development/issues/15 for more information
