### ISSUE TITLE
Release notes (wrongly) mention multi-tier alba

### ISSUE THREAD

**Issue by domsj** [openvstorage/home#18]
A cache and a tier are not the same thing, see e.g. https://storageswiss.com/2014/01/15/whats-the-difference-between-tiering-and-caching/ .
What alba provides is caching (using a flash alba in front of hdd alba as a fragment __cache__), not tiering.
Unless we add tiering the release notes should be updated accordingly.

**Comment by wimpers** [comment]
Valid point
