### ISSUE TITLE
Config management in Arakoon

### ISSUE THREAD

**Issue by wimpers** [openvstorage/home#19]
In Fargo we support the open-source ETCD project as component to hold the configs of all Open vStorage componets. Next to ETCD it should also be possible to store the config file in Arakoon, our own distributed KV DB. Decision between Arakoon and ETCD is made at install time of the first node and can't be changed afterwards.

**Comment by wimpers** [comment]
Planned in https://github.com/ovs-projects/org_development/issues/44

**Comment by JeffreyDevloo** [comment]
### Information
We currently use arakoon as our deploy configuration management. Testing is mainly done with arakoon as configuration management aswell.
