### ISSUE TITLE
new landing page for OVS.org site

### ISSUE THREAD

**Issue by despiegk** [openvstorage/home#2]
like
https://minio.io/

**Comment by tbogaert** [comment]
http://test.openvstorage.org/

Something like this, I assume

**Comment by despiegk** [comment]
cool like it

On Thu, Mar 10, 2016 at 7:59 PM, tbogaert <notifications@github.com> wrote:

> http://test.openvstorage.org/
>
> Something like this, I assume
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openvstorage/home/issues/2#issuecomment-194923265>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk
