### ISSUE TITLE
64TB vdisks

### ISSUE THREAD

**Issue by wimpers** [openvstorage/home#29]
Currently vDisks are limited to 2TB. With this ticket we want to up the limit to 64TB per vDisks.

Todo:
- Update default max size in the voldr to 64TB
- Limit the GUI and API so no disks larger than 64TB can be created.

No need to make the setting configurable per vPool for now.

**Comment by wimpers** [comment]
Anything to do Edge side?

**Comment by wimpers** [comment]
Related https://github.com/openvstorage/framework/issues/830 for the scrubbing.

**Comment by redlicha** [comment]
Another issue to address when supporting large volumes is the amount of metadata. This can be addressed by
* using a bigger cluster size for large volumes. Currently volumedriver allows to configure the cluster size per volumedriver cluster (vpool).
* using multiple metadata servers inside a volumedriver instance: the metadata per volume will still be inside the same database, but different volumes can be hosted by different databases. This can be achieved by configuring multiple MDS instances per volumedriver instance.

**Comment by wimpers** [comment]
Framework side https://github.com/openvstorage/framework/pull/886 is done. Awaiting voldrv side (cc @redlicha )

**Comment by redlicha** [comment]
Can be tested with voldrv dev builds as of 6.0.4-dev.201609081220.d94a65 (not in a repo yet, get it directly from jenkins).

**Comment by kinvaris** [comment]
PASSED:

Passed in new CI test called `deployment_vdisk_test`, in this test we deploy these sizes of volumes `[2147483648000, 4294967296000, 8589934592000, 17179869184000, 34359738368000, 68719476736000]` through these ways: `truncate, api, qemu-img create`
```
({'ci.scenarios.vDisk.deployment_vdisk_test': {'case_type': 'FUNCTIONALITY',
   'errors': None,
   'status': 'PASSED'}},
 None)
```
