### ISSUE TITLE
Revive CentOS support

### ISSUE THREAD

**Issue by wimpers** [openvstorage/home#49]
Revive CentOS support:
* [ ] Fix dependency problem https://github.com/openvstorage/framework/issues/1184 https://github.com/openvstorage/volumedriver/issues/210
* [ ]  revive automated testing on CentOS

**Comment by dejonghb** [comment]
https://github.com/openvstorage/framework/blob/master/packaging/redhat/cfgs/openvstorage-core.cfg#L11

aptdaemon is ubuntu/debian specific; does not exist on centos/redhat systems

**Comment by toolslive** [comment]
For what concerns alba: epel moved to
http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm.
and the current arakoon 1.9.15 package uses 7-8, while alba 1.3.4 uses 7-9. They don't like each other. I've created an arakoon.1.9.5_for_alba_1.3.4 rpm package.
It's here:
https://github.com/openvstorage/arakoon/releases/tag/1.9.15

If you need to install alba 1.3.4 on centos-7, please use that specific arakoon package.

**Comment by run283092610** [comment]
how can i install  aptdaemon and volumedriver-no-dedup-server in centos7
openvstorage-core depends on this packages

**Comment by wimpers** [comment]
Hi run283092610 ,

the latest OVS version no longer works on CentOS and there is currently no plan to get the OVS functionality working again. Best approach is to use Ubuntu 16.04 to run OVS.

**Comment by wimpers** [comment]
Closing this one down. Create a new ticket if needed.
