### ISSUE TITLE
Minimal environment running in docker

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/home#5]
Create dockers for
- etcd
- arakoon
- Alba
- Framework components
- Volumedriver
...

Use docker compose(only for local node) or Ansible for orchestration on multiple nodes

**Comment by dejonghb** [comment]
There's an hyperconverged dockerised setup available via https://github.com/openvstorage/docker-tools/tree/master/hyperconverged which is easier than all items in different containers.
