### ISSUE TITLE
Multiple ASDs per device

### ISSUE THREAD

**Issue by wimpers** [openvstorage/home#6]
Since the performance is limited per ASD to around 10K gets/s the full bandwidth of an SSD isn't used in case we have a 1-1 relation for ASDs and SSD devices. 

To make full use of an SSD in the flash accelerated ALBA  (ALBA performance tier on SSD) wa can have multiple ASDs per SSD. The amount of ASDs per device can be a fixed setting (etcd) and doesn't need to be updatable. No need to expose this setting in the GUI for now.

Possible ways to tackle this:
* Partition the SSD and have an ASD per partition (less flexible).
* As ASDs can work on directory level, so we could have an ASD per directory. This has as benefit that you are flexible. The drawback is that the rebalancing will need some rework in that case I believe (@toolslive , @domsj ?)

**Comment by domsj** [comment]
Having multiple asds per ssd could work.
We may want to have knowledge about the fact that this is going on, so that we can keep this in mind when doing fragment placement, and (as you were referring to) to avoid useless rebalancing

**Comment by khenderick** [comment]
Can we run into issues here that all ASDs using just folders on the same partition will try to use all space available? E.g. on a 1TiB disk with 10 ASDs that they all think they have 1TiB instead of 100GiB?

**Comment by domsj** [comment]
Currently all asds will indeed think they have 1TiB of disk space to fill, however they'll also think they've each filled up 400GB when the disk is 400GB full.
I would feel most comfortable if all disks get their own partition.

**Comment by wimpers** [comment]
Just as a side note: it is ok to limit the scope so that multiple ASDs on the same device can only be attached to a single backend. We can always extend the scope later if needed imho.
