### ISSUE TITLE
Have a shared SAS bus available on the storage nodes using SAS disks

### ISSUE THREAD

**Issue by lzonneke** [openvstorage/home#8]
GreenitGlobe is working with Quanta storage servers of 70 disks divided between two nodes. The purpose here is to have a complete redundant set up on storage level.

Both physical nodes should work independent but should see all the disks in case of a failure of the node. In that case when a node goes down it will not have the 35 disks but it will take over the other 35 disks of the second node having 70 disks on one node. In that case the node which is still live needs o take over the alba's of the failed node.

**Comment by lzonneke** [comment]
@wimpers can you please comment if this feature request is approved and if it is on the planning?

If so can you please state the version in which this feature is planned for?

**Comment by saelbrec** [comment]
@lzonneke ,

Do both systems see all disks at all times?
If only in case of failure access is moved over, is this a manual action or does that happen automatically?
What about the fail back when node1 resumes operation?
What happens networking wise, are the ip addresses moved over to node2 as well?
Also be aware that each node should be spec’ed(cpu/memory) to drive the 70 disks. Cause if they aren’t you might be better of temporary falling back to a less optimal policy instead.

I think we need to put our heads together so we can get a better insight on what we can rely or not.

**Comment by lzonneke** [comment]
*Do both systems see all disks at all times?*
yes 
*If only in case of failure access is moved over, is this a manual action or does that happen automatically?*
automatically 
*What about the fail back when node1 resumes operation?*
then a re balance needs to be done between both nodes
*What happens networking wise, are the ip addresses moved over to node2 as well?*
 Why move? the IP would not be reachable any more, when the node comes back then we should re balance again and the IP should come back...
*Also be aware that each node should be spec’ed(cpu/memory) to drive the 70 disks. Cause if they aren’t you might be better of temporary falling back to a less optimal policy instead.*
I think we could accept a less optimal policy during the time of the failure 
*I think we need to put our heads together so we can get a better insight on what we can rely or not.*
Let me know when you like to discuss

**Comment by lzonneke** [comment]
this feature request can be closed, we will use a double amount of HW with 3/4 erasure

@despiegk I have been told you have discussed this with Jan DL
