### ISSUE TITLE
ALBA on RDMA

### ISSUE THREAD

**Issue by wimpers** [openvstorage/home#9]
In order to improve the performance of ALBA and lower the latency for reads, let ALBA communicate over [RDMA](https://en.wikipedia.org/wiki/Remote_direct_memory_access). The RDMA implementation is based upon librdmacm, high-performance asynchronous reliable messaging and RPC library.

Note: this requires RDMA capable hardware.

**Comment by wimpers** [comment]
Please close if packages are delivered.

**Comment by domsj** [comment]
This is available as of alba 0.9.6, which has been released (and pushed to unstable)
